Models/Catalog/AssetDetailModel.cs
using LibraryData.Models;
using System.Collections.Generic;

namespace Library.Models.Catalog
{
    public class AssetDetailModel
    {
        public int AssetId { get; set; }
        public string Title { get; set; }
        public string AuthorOrDirector { get; set; }
        public string Type { get; set; }
        public int Year { get; set; }
        public string ISBN { get; set; }
        public string DeweyCallNumber { get; set; }
        public string Status { get; set; }
        public decimal Cost { get; set; }
        public string CurrentLocation { get; set; }
        public string ImageUrl { get; set; }
        public string PatronName { get; set; }
        public Checkout LatestCheckout { get; set; }
        public IEnumerable<CheckoutHistory> CheckoutHistory { get; set; }
        public IEnumerable<AssetHoldModel> CurrentHolds { get; set; }
    }

    public class AssetHoldModel
    {
        public string PatronName { get; set; }
        public string HoldPlaced { get; set; }

    }
}

Models/Catalog/AssetIndexListingModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Library.Models.Catalog
{
    public class AssetIndexListingModel
    {

        public int Id { get; set; }
        public string ImageUrl { get; set; }
        public string Title { get; set; }
        public string AuthorOrDirector { get; set; }
        public string Type { get; set; }
        public string DeweyCallNumber { get; set; }
        public string NumberOfCopies { get; set; }

    }
}

Models/Catalog/AssetIndexModel.cs
using System.Collections.Generic;

namespace Library.Models.Catalog
{
    public class AssetIndexModel
    {
        public IEnumerable<AssetIndexListingModel> Assets { get; set; }

    }
}

Controllers/CatalogController.cs
using Library.Models.Catalog;
using Library.Models.CheckoutModels;
using LibraryData;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace Library.Controllers
{
    public class CatalogController : Controller
    {
        private ILibraryAsset _assets;
        private ICheckout _checkouts;        
        public CatalogController(ILibraryAsset assets, ICheckout checkouts)
        {
            _assets = assets;
            _checkouts = checkouts;
        }

        public IActionResult Index()
        {
            var assetModels = _assets.GetAll();

            var listingResult = assetModels
                .Select(result => new AssetIndexListingModel
                {
                    Id = result.Id,
                    ImageUrl = result.ImageUrl,
                    AuthorOrDirector = _assets.GetAuthorOrDirector(result.Id),
                    DeweyCallNumber = _assets.GetDeweyIndex(result.Id),
                    Title = result.Title,
                    Type = _assets.GetType(result.Id)
                });

            var model = new AssetIndexModel()
            {
                Assets = listingResult
            };

            return View(model);

        }
    
        public IActionResult Detail(int id)
        {
            var asset = _assets.GetById(id);

            var currentHolds = _checkouts.GetCurrentHolds(id)
                .Select(a => new AssetHoldModel
                {
                    HoldPlaced = _checkouts.GetCurrentHoldPlaced(a.Id).ToString("d"),
                    PatronName = _checkouts.GetCurrentHoldPatronName(a.Id)
                });
            var model = new AssetDetailModel
            {
                AssetId = id,
                Title = asset.Title,
                Year = asset.Year,
                Cost = asset.Cost,
                Status = asset.Status.Name,
                ImageUrl = asset.ImageUrl,
                AuthorOrDirector = _assets.GetAuthorOrDirector(id),
                CurrentLocation = _assets.GetCurrentLocation(id).Name,
                DeweyCallNumber = _assets.GetDeweyIndex(id),
                ISBN = _assets.GetIsbn(id),
                CheckoutHistory = _checkouts.GetCheckoutHistory(id),
                LatestCheckout = _checkouts.GetLatestCheckout(id),
                PatronName = _checkouts.GetCurrentCheckoutPatron(id),
                CurrentHolds = currentHolds

            };

            return View(model);

        }

        public IActionResult CheckIn(int id)
        {
            _checkouts.CheckInItem(id);
            return RedirectToAction("Detail", new { id = id });
        }
        public IActionResult Checkout(int id)
        {
            var asset = _assets.GetById(id);

            var model = new CheckoutModel
            {
                AssetId = id,
                ImageUrl = asset.ImageUrl,
                Title = asset.Title,
                LibraryCardId = "",
                IsCheckedOut = _checkouts.IsCheckedOut(id)
            };

            return View(model);
        }

        public IActionResult Hold(int id)
        {
            var asset = _assets.GetById(id);

            var model = new CheckoutModel
            {
                AssetId = id,
                ImageUrl = asset.ImageUrl,
                Title = asset.Title,
                LibraryCardId = "",
                IsCheckedOut = _checkouts.IsCheckedOut(id),
                HoldCount = _checkouts.GetCurrentHolds(id).Count()
            };

            return View(model);
        }

        public IActionResult MarkLost(int assetId)
        {
            _checkouts.MarkLost(assetId);
            return RedirectToAction("Detail", new { id = assetId });
        }

        public IActionResult MarkFound(int assetId)
        {
            _checkouts.MarkFound(assetId);
            return RedirectToAction("Detail", new { id = assetId });
        }

        [HttpPost]
        public IActionResult PlaceCheckout(int assetId, int libraryCardId)
        {
            _checkouts.CheckOutItem(assetId, libraryCardId);

            return RedirectToAction("Detail", new { id = assetId });

        }

        [HttpPost]
        public IActionResult PlaceHold(int assetId, int libraryCardId)
        {
            _checkouts.PlaceHold(assetId, libraryCardId);

            return RedirectToAction("Detail", new { id = assetId });

        }

    }
}

Views/Catalog/Checkout.cshtml
@model Library.Models.CheckoutModels.CheckoutModel

@section Scripts{
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
}

@section Styles{
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
}

<div class="container">
    <div class="header clearfix detailHeading">
        <h2 class="text-muted">Checkout Library Item</h2>
    </div>

    <div class="jumbotron">
        <div class="row">
            <div class="col-md-3">
                <div>
                    <p id="itemTitle">@Model.Title</p>
                    <img class="detailImage" src="@Model.ImageUrl" />
                </div>
            </div>
            @*you could also use tag helpers.*@
            <div class="col-md-9">
                @*this is an html helper - it creates an object that implements idisposable*@
                @using (Html.BeginForm("PlaceCheckout", "Catalog", FormMethod.Post))
                {
                    @Html.HiddenFor(a => a.AssetId)
                    <div>
                        Please insert a Library Card ID.
                        @Html.TextBoxFor(a => a.LibraryCardId)
                        @*write out a text box and set attributes according to info in the model*@
                    </div>
                    <div>
                        <button type="submit" class="btn btn-success btn-lg">Check out</button>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Views/Catalog/Detail.cshtml
@model Library.Models.Catalog.AssetDetailModel


    <div class="container">
        <div class="page-header clearfix detailHeading">
            <h2 class="text-muted">View Library Item</h2>
        </div>

        <div class="jumbotron">
            <div class="row">
                <div class="col-md-4">
                    <div>
                        <img class="detailImage" src="@Model.ImageUrl" />
                    </div>
                </div>
                <div class="col-md-4">
                    <p id="itemTitle">@Model.Title</p>
                    <p id="itemAuthor">@Model.AuthorOrDirector</p>
                    <p id="itemStatus">@Model.Status</p>
                    <p id="itemType">@Model.Type</p>
                    <p id="itemLocation">@Model.CurrentLocation</p>

                    @if (Model.Status == "Lost")
                    {
                        <p>This item has been lost. It cannot be checked out.</p>
                        <p><a class="btn btn-lg btn-danger" role="button" asp-controller="Catalog" asp-action="MarkFound" asp-route-id="@Model.AssetId">Mark Item Found</a></p>
                    }

                    @if (Model.Status == "Checked Out")
                    {
                        <p id="itemPatron">Checked Out By: @Model.PatronName</p>
                        <p><a class="btn btn-lg btn-success" role="button" asp-controller="Catalog" asp-action="CheckIn" asp-route-id="@Model.AssetId">Check In</a></p>
                        <p><a class="btn btn-lg btn-warning" role="button" asp-controller="Catalog" asp-action="Hold" asp-route-id="@Model.AssetId">Place Hold</a></p>
                    }

                    @if (Model.Status == "Available")
                    {
                        <p><a class="btn btn-lg btn-info" role="button" asp-controller="Catalog" asp-action="Checkout" asp-route-id="@Model.AssetId">Check out</a></p>
                    }
                </div>
            </div>
            <div class="col-md-4 detailInfo">
                <table>
                    <tr>
                        <td class="itemLabel">ISBN: </td>
                        <td class="itemValue">@Model.ISBN</td>
                    </tr>
                    <tr>
                        <td class="itemLabel">Call Number: </td>
                        <td class="itemValue">@Model.DeweyCallNumber</td>
                    </tr>
                    <tr>
                        <td class="itemLabel">Replacement Cost: </td>
                        <td class="itemValue">@Model.Cost</td>
                    </tr>
                </table>
            </div>

        </div>

        <div class="row">
            <div class="col-lg-6">
                <h4>Checkout History</h4>
                <table class="table table-bordered table-hover table-condensed">
                    <thead>
                        <tr>
                            <th>Date Loaned</th>
                            <th>Date Returned</th>
                            <th>Card Id</th>
                        </tr>   
                    </thead>
                    <tbody>
                        @foreach (var checkout in @Model.CheckoutHistory)
                        {
                            <tr>
                                <td>
                                    @checkout.CheckedOut
                                </td>
                                <td>
                                    @checkout.CheckedIn
                                </td>
                                <td>
                                    @checkout.LibraryCard.Id
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <div class="col-lg-6">
                <h4>Current Holds</h4>
                <table class="table table-bordered table-hover table-condensed">
                    <thead>
                        <tr>
                            <th>Hold Placed</th>
                            <th>Patron</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var hold in @Model.CurrentHolds)
                        {
                            <tr>
                                <td>
                                    @hold.HoldPlaced
                                </td>
                                <td>
                                    @hold.PatronName
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

Views/Catalog/Hold.cshtml
@model Library.Models.CheckoutModels.CheckoutModel
@{
    ViewBag.Title = @Model.Title;
}

@*@model is the model directive*@

@section Scripts{
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
}

@section Styles{
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
}

<div class="container">
    <div class="header clearfix detailHeading">
        <h2 class="text-muted">Place Hold on Library Item</h2>
    </div>

    <div class="jumbotron">
        <div class="row">
            <div class="col-md-3">
                <div>
                    <p id="itemTitle">@Model.Title</p>
                    <img class="detailImage" src="@Model.ImageUrl" />
                </div>
            </div>
            @*you could also use tag helpers.*@
            <div class="col-md-9">
                <p>There are currently @Model.HoldCount holds in the queue for this item.</p>
                @*this is an html helper - it creates an object that implements idisposable*@
                @using (Html.BeginForm("PlaceHold", "Catalog", FormMethod.Post))
                {
                    @Html.HiddenFor(a => a.AssetId)
                    <div>
                        Please insert a Library Card ID.
                        @Html.TextBoxFor(a => a.LibraryCardId)
                        @*write out a text box and set attributes according to info in the model*@
                    </div>
                    <div>
                        <button type="submit" class="btn btn-info btn-lg">Place Hold</button>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Views/Catalog/Index.cshtml
@model Library.Models.Catalog.AssetIndexModel

<div id="assets">
    <h3>Library Catalog</h3>
    <div id="assetsTable">
        <table class="table table-condensed" id="catalogIndexTable">
            <thead>
                <tr>
                    <th>Image</th>
                    <th>Title</th>
                    <th>Author / Director</th>
                    <th>Dewey Call Number</th>
                </tr>
            </thead>
            <tbody>
                @foreach(var asset in Model.Assets)
                {
                <tr class="assetRow">
                    <td class="">
                        <a asp-controller="Catalog" asp-action="Detail" asp-route-id="@asset.Id">
                            <img src="@asset.ImageUrl" class="imageCell"/>
                        </a>
                    </td>
                    <td class="">@asset.Title</td>
                    <td class="">@asset.AuthorOrDirector</td>
                    <td class="">@asset.DeweyCallNumber</td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>