Models/Patron/PatronDetailModel.cs
using LibraryData.Models;
using System;
using System.Collections.Generic;

namespace Library.Models.Patron
{
    public class PatronDetailModel
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName{

            get
            {
                return FirstName + " " + LastName;
            }

        }

        public int LibraryCardId { get; set; }
        public string Address { get; set; }
        public DateTime MemberSince { get; set; }
        public string Telephone { get; set; }
        public string HomeLibraryBranch { get; set; }
        public decimal OverdueFees { get; set; }
        public IEnumerable<Checkout> AssetsCheckedOut { get; set; }
        public IEnumerable<CheckoutHistory> CheckoutHistory { get; set; }
        public IEnumerable<Hold> Holds { get; set; }


    }
}

Models/Patron/PatronIndexModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Library.Models.Patron
{
    public class PatronIndexModel
    {
        public IEnumerable<PatronDetailModel> Patrons { get; set; }
    }
}

Controllers/PatronController.cs
using Library.Models.Patron;
using LibraryData;
using LibraryData.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace Library.Controllers
{
    public class PatronController : Controller
    {

        private IPatron _patron;
        public PatronController(IPatron patron)
        {
            _patron = patron;
        }

        public IActionResult Index()
        {
            var allPatrons = _patron.GetAll();

            var patronModels = allPatrons.Select(p => new PatronDetailModel
            {
                Id = p.Id,
                FirstName = p.FirstName,
                LastName = p.LastName,
                LibraryCardId = p.LibraryCard.Id,
                OverdueFees = p.LibraryCard.Fees,
                HomeLibraryBranch = p.HomeLibraryBranch.Name

            }).ToList();

            var model = new PatronIndexModel() { Patrons = patronModels };

            return View(model);

        }

        public IActionResult Detail(int id)
        {
            var patron = _patron.Get(id);

            var model = new PatronDetailModel
            {
                LastName = patron.LastName,
                FirstName = patron.FirstName,
                Address = patron.Address,
                HomeLibraryBranch = patron.HomeLibraryBranch.Name,
                MemberSince = patron.LibraryCard.Created,
                OverdueFees = patron.LibraryCard.Fees,
                LibraryCardId = patron.LibraryCard.Id,
                Telephone = patron.TelephoneNumber,
                AssetsCheckedOut = _patron.GetCheckouts(id).ToList() ?? new List<Checkout>(),
                CheckoutHistory = _patron.GetCheckoutHistory(id),
                Holds = _patron.GetHolds(id)
            };

            return View(model);
        }
    }
}

Views/Patron/Detail.cshtml
@model Library.Models.Patron.PatronDetailModel
    <div class="container">
        <div class="header clearfix detailHeading">
            <h2 class="text-muted">Patron Information</h2>
        </div>
        <div class="jumbotron">
            <div class="row">
                <div class="col-md-4">
                    <div>
                        <h2>@Model.FirstName @Model.LastName</h2>
                        <div class="patronContact">
                            <div id="patronTel">Library Card ID: @Model.LibraryCardId</div>
                            <div id="patronAddress">Address: @Model.Address</div>
                            <div id="patronTel">Telephone: @Model.Telephone</div>
                            <div id="patronDate">Member Since: @Model.MemberSince</div>
                            <div id="patronLibrary">Home Library: @Model.HomeLibraryBranch</div>
                            @if (@Model.OverdueFees > 0)
                            {
                                <div id="patronHasFees">Current Fees Due: $@Model.OverdueFees</div>
                            }
                            else
                            {
                                <div id="patronNoFees">No Fees Currently Due.</div>

                            }
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <h4>Assets Currently Checked Out</h4>
                    @if (@Model.AssetsCheckedOut.Any())
                    {
                        <div id="patronAssets">
                            <ul>
                                @foreach (var checkout in @Model.AssetsCheckedOut)
                                {
                                    <li>
                                        @checkout.LibraryAsset.Title - (Library Asset ID: @checkout.LibraryAsset.Id)
                                        <ul>
                                            <li>
                                                Since: @checkout.Since
                                            </li>
                                            <li>
                                                Due: @checkout.Until
                                            </li>
                                        </ul>
                                    </li>
                                }
                            </ul>
                        </div>
                    }
                    else
                    {
                        <div>No items currently checked out.</div>

                    }
                </div>

                <div class="col-md-4">
                    <h4>Assets Currently On Hold</h4>
                    @if (@Model.Holds.Any())
                    {
                        <div id="patronHolds">
                            <ul>
                                @foreach (var hold in @Model.Holds)
                                {
                                    <li>@hold.LibraryAsset.Title - Placed @hold.HoldPlaced.ToString("yy-dd-MM - HH:mm")</li>
                                }
                            </ul>
                        </div>
                    }
                    else
                    {
                        <div>No items on hold.</div>
                    }
                </div>
            </div>
        </div>
    </div>

Views/Patron/Index.cshtml
@model Library.Models.Patron.PatronIndexModel
@{ 
    ViewBag.Title = "Patron Index";
}

<h3>@ViewBag.Title</h3>
<div id="patronIndex">
    <table class="mdl-data-table mdl-js-data-table mdl-data-table--selectable mdl-shadow--2dp customTable" id="patronIndexTable">
        <thead>
            <tr>
                <th>Profile Link</th>
                <th>Last Name</th>
                <th>First Name</th>
                <th>Library Card Id</th>
                <th>Overdue Fees</th>
                <th>Home Library</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var patron in Model.Patrons)
            {
                <tr>
                    <td><a asp-controller="Patron" asp-action="Detail" asp-route-id="@patron.Id">(Profile)</a></td>
                    <td>@patron.LastName</td>
                    <td>@patron.FirstName</td>
                    <td>@patron.LibraryCardId</td>
                    <td>@patron.OverdueFees</td>
                    <td>@patron.HomeLibraryBranch</td>
                </tr>
             }
        </tbody>
    </table>
</div>