Models/Branch/BranchDetailModel.cs
using System.Collections.Generic;

namespace Library.Models.Branch
{
    public class BranchDetailModel
    {

        public int Id { get; set; }
        public string Address { get; set; }
        public string Name { get; set; }
        public string OpenDate { get; set; }
        public string Telephone { get; set; }
        public bool IsOpen { get; set; }
        public string Description { get; set; }
        public int NumberOfPatrons { get; set; }
        public int NumberOfAssets { get; set; }
        public decimal TotalAssetValue { get; set; }
        public string ImageUrl { get; set; }
        public IEnumerable<string> HoursOpen { get; set; }

    }
}

Models/Branch/BranchIndexModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Library.Models.Branch
{
    public class BranchIndexModel
    {
        public IEnumerable<BranchDetailModel> Branches { get; set; }

    }
}

Controllers/BranchController.cs
using Library.Models.Branch;
using LibraryData;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Library.Controllers
{
    public class BranchController : Controller
    {
        private ILibraryBranch _branch;
        public BranchController(ILibraryBranch branch)
        {
            _branch = branch;
        }
        public IActionResult Index()
        {
            var branches = _branch.GetAll().Select(branch => new BranchDetailModel
            {
                Id = branch.Id,
                Name = branch.Name,
                IsOpen = _branch.IsBranchOpen(branch.Id),
                NumberOfAssets = _branch.GetAssets(branch.Id).Count(),
                NumberOfPatrons = _branch.GetPatrons(branch.Id).Count()

            });

            var model = new BranchIndexModel
            {
                Branches = branches
            };
            return View(model);
        }

        public IActionResult Detail(int id)
        {
            var branch = _branch.Get(id);

            var model = new BranchDetailModel {

                Id = branch.Id,
                Name = branch.Name,
                Address = branch.Address,
                Telephone = branch.Telephone,
                OpenDate = branch.OpenDate.ToString("yyyy-MM-dd"),
                NumberOfAssets = _branch.GetAssets(id).Count(),
                NumberOfPatrons = _branch.GetPatrons(id).Count(),
                TotalAssetValue = _branch.GetAssets(id).Sum(a => a.Cost),
                ImageUrl = branch.ImageUrl,
                HoursOpen = _branch.GetBranchHours(id)
            };

            return View(model);
        }
    }
}

Views/Branch/Detail.cshtml
@model Library.Models.Branch.BranchDetailModel

@{ 
    ViewBag.Title = Model.Name + " Branch";
}

<div class="container">
    <div class="header clearfix detailHeading">
        <h2 class="text-muted">Branch Information</h2>
    </div>
    <div class="jumbotron">
        <div class="row">
            <img src="@Model.ImageUrl"/>
        </div>
        <div class="row branchInfo">
            <div class="col-md-8">
                <h2>@Model.Name</h2>
                <div class="branchContact">
                    <div id="branchAddress">Address: @Model.Address</div>
                    <div id="branchTel">Telephone: @Model.Telephone</div>
                </div>
                <div id="branchDescription">
                    <p class="caption">@Model.Description</p>
                </div>
                <div id="branchHours">
                    <ul>
                        @foreach(var day in Model.HoursOpen)
                        {
                            <li>@day</li>
                        }
                    </ul>
                </div>
            </div>
            <div class="col-md-4">
                <table>
                    <tr>
                        <td class="itemLabel">Date Opened: </td>
                        <td class="itemValue">@Model.OpenDate</td>
                    </tr>
                    <tr>
                        <td class="itemLabel">Number Of Patrons: </td>
                        <td class="itemValue">@Model.NumberOfPatrons</td>
                    </tr>
                    <tr>
                        <td class="itemLabel">Number of Assets: </td>
                        <td class="itemValue">@Model.NumberOfAssets</td>
                    </tr>
                    <tr>
                        <td class="itemLabel">Value of Assets: </td>
                        <td class="itemValue">$@Model.TotalAssetValue</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>

</div>

Views/Branch/Index.cshtml
@model Library.Models.Branch.BranchIndexModel
@{ 
    ViewBag.Title = "Branch Index";
} 

<h3>@ViewBag.Title</h3>
<div id="branchIndex">
    <table class="mdl-data-table mdl-js-data-table mdl-data-table--selectable mdl-shadow--2dp customTable" id="branchIndexTable">
        <thead>
            <tr>
                <th>Branch Name</th>
                <th>Open Now</th>
                <th>Number Of Assets</th>
                <th>Number of Patrons</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var branch in Model.Branches)
            {
                <tr>
                    <td class="strongTd"><a asp-controller="Branch" asp-action="Detail" asp-route-id="@branch.Id">@branch.Name</a></td>
                    <td>@branch.IsOpen</td>
                    <td>@branch.NumberOfAssets</td>
                    <td>@branch.NumberOfPatrons</td>
                </tr>
            }
        </tbody>
    </table>
</div>